# =====================================================================
# Flower app configuration
# https://flower.ai/docs/framework/how-to-configure-pyproject-toml.html
# =====================================================================

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ddl-flower-app"
version = "1.0.0"
description = "Federated Learning app"
license = "Apache-2.0"

dependencies = [
    "flwr[simulation]>=1.22.0",
    "flwr-datasets[vision]>=0.5.0",
    "torch==2.7.1",
    "torchvision==0.22.1",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "nxhxl"

[tool.flwr.app.components]
serverapp = "fl_app.server_app:app"
clientapp = "fl_app.client_app:app"

# -----------------------------------------------------
# Run config (передаётся в context.run_config)
# -----------------------------------------------------
[tool.flwr.app.config]
# Data
dataset = "cifar10"       # cifar10 | mnist
data-dir = "data/"

# Partitioning
scheme = "iid"              # "iid" | "dirichlet"
alpha = 0.3                 # используется только при scheme="dirichlet"
seed = 42
min-partition-size = 0

# Federated selection
fraction-train = 1.0
fraction-evaluate = 0.0     # <-- важно: клиенты НЕ валидируют (валидация на сервере через evaluate_fn)

# Aggregation strategy
aggregation = "fedadam"          # варианты: fedavg; fedavgm; fedadam; fedyogi; fedadagrad; fedmedian; fedtrimmedavg; krum; multikrum; bulyan
# --- опционально, параметры под стратегии ---
server-learning-rate = 1.0      # для fedavgm
server-momentum = 0.9           # для fedavgm

server-eta = 0.01               # для fedadam/fedyogi/fedadagrad (server lr)
server-eta-l = 0.001            # "client lr" параметр FedOpt (обычно = реальному lr клиента)
server-beta1 = 0.9              # fedadam/fedyogi
server-beta2 = 0.99             # fedadam/fedyogi
server-tau = 1e-9               # fedadam/fedyogi/fedadagrad

trimmed-beta = 0.2              # fedtrimmedavg
num-malicious-nodes = 0         # krum/multikrum/bulyan
num-nodes-to-select = 1         # multikrum

#logs
num-clients = 10
partition-plot-type = "heatmap"   # или "bar"
partition-size-unit = "percent"   # или "absolute"

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 10
options.num-rounds = 10  
options.backend.client-resources.num-cpus = 2
options.backend.client-resources.num-gpus = 1.0  # если нет GPU — поставь 0.0
